export const BANNER_ITEMS = [
  {
    title:
      "다시 깊게 익히는 인사이드 리액트 - AI 시대에도 대체 불가능한 개발자로 살아가는 프론트엔드 핵심 역량, React 프로그래밍 구조와 원리",
    link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=369729972&amp;partner=openAPI&amp;start=api",
    author: "윤재원(단테) (지은이)",
    pubDate: "2025-08-20",
    description:
      "프론트엔드 개발자들이 복잡한 웹 개발 환경에서 마주하는 문제들을 해결하고, 실제 애플리케이션을 효율적으로 구축할 수 있도록 돕는 리액스 중급서다. 프론트엔드 기술이 왜, 어떻게 발전해왔는지 변천사를 이해함으로써, 웹 애플리케이션의 뼈대를 이루는 UI 컴포넌트를 설계하고 재사용성을 높이는 방법, 상태와 반응성을 통해 예측 가능한 UI를 만드는 원리를 알려준다.",
    isbn: "K332030823",
    isbn13: "9791194383376",
    itemId: 369729972,
    priceSales: 37800,
    priceStandard: 42000,
    mallType: "BOOK",
    stockStatus: "",
    mileage: 2100,
    cover:
      "https://image.aladin.co.kr/product/36972/99/coversum/k332030823_1.jpg",
    categoryId: 6627,
    categoryName:
      "국내도서>컴퓨터/모바일>프로그래밍 개발/방법론>웹 서비스/웹 프로그래밍",
    publisher: "골든래빗(주)",
    salesPoint: 860,
    adult: false,
    fixedPrice: true,
    customerReviewRank: 10,
    subInfo: {},
  },
  {
    title:
      "프론트엔드 개발자를 위한 인터랙티브 웹 애니메이션 - HTML, CSS, JavaScript 기본기부터 React, Three.js를 활용한 3D 애니메이션까지",
    link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=366642748&amp;partner=openAPI&amp;start=api",
    author: "김영민 (지은이)",
    pubDate: "2025-07-01",
    description:
      "웹 개발 책 중에서도 실무에서 즉시 활용 가능한 내용을 담고 있다. 실제로 사용되는 애니메이션 효과를 구현해 보면서, 구현 방법과 함께 기술적인 이해를 동시에 학습할 수 있다. 또한, 사용자 경험(UX)을 중요하게 다루며 애니메이션을 적용하는 방법과 사용자 경험을 개선하는 방법에 대해 설명한다.",
    isbn: "8931479395",
    isbn13: "9788931479393",
    itemId: 366642748,
    priceSales: 34200,
    priceStandard: 38000,
    mallType: "BOOK",
    stockStatus: "",
    mileage: 1900,
    cover:
      "https://image.aladin.co.kr/product/36664/27/coversum/8931479395_1.jpg",
    categoryId: 6355,
    categoryName: "국내도서>컴퓨터/모바일>웹디자인/홈페이지>HTML/JavaScript",
    publisher: "영진.com(영진닷컴)",
    salesPoint: 349,
    adult: false,
    fixedPrice: true,
    customerReviewRank: 10,
    subInfo: {},
    isfavorit: false,
  },
  {
    title:
      "우아한 타입스크립트 with 리액트 - 배달의민족 개발 사례로 살펴보는 우아한형제들의 타입스크립트와 리액트 활용법",
    link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=327063952&amp;partner=openAPI&amp;start=api",
    author:
      "우아한형제들 웹프론트개발그룹, 권기석, 권세진, 고우혁, 김정혁, 박선희, 서그림, 송지은, 송하영, 심문성, 이정민, 이수연, 이예지, 이강열, 조은현, 최현준, 황윤서 (지은이), 김민태 (감수)",
    pubDate: "2023-10-31",
    description:
      "우아한형제들의 실제 코드를 기반으로 타입스크립트의 기본 개념 및 특성과 리액트 환경에서의 타입스크립트 활용법을 알려준다. 또한 배달의민족 개발 사례와 우아한형제들 구성원의 인터뷰를 통해 실무에 바로 적용할 수 있는 다양한 기술 활용 팁을 소개한다.",
    isbn: "K332936775",
    isbn13: "9791169211567",
    itemId: 327063952,
    priceSales: 28800,
    priceStandard: 32000,
    mallType: "BOOK",
    stockStatus: "",
    mileage: 1600,
    cover:
      "https://image.aladin.co.kr/product/32706/39/coversum/k332936775_1.jpg",
    categoryId: 6355,
    categoryName: "국내도서>컴퓨터/모바일>웹디자인/홈페이지>HTML/JavaScript",
    publisher: "한빛미디어",
    salesPoint: 1888,
    adult: false,
    fixedPrice: true,
    customerReviewRank: 9,
    subInfo: {},
    isfavorit: false,
  },
  {
    title:
      "대규모 리액트 웹 앱 개발 - 확장 가능한 대규모 자바스크립트 웹 애플리케이션을 구축하는 방법",
    link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=355972441&amp;partner=openAPI&amp;start=api",
    author: "애디 오스마니, 하산 지르데 (지은이), 김모세 (옮긴이)",
    pubDate: "2025-02-07",
    description:
      "거대 괴수가 되어버린 자바스크립트 웹 개발로부터 살아남는 방법. 오늘날 대규모 웹 앱 개발의 어려움을 극복하기 위해서는 알아야 할 게 많다. 이 책은 모던 웹 개발의 핵심 개념 및 최신 도구와 기술을 소개하고 이에 맞춰 리액트를 활용하는 법을 다룬다.",
    isbn: "K862036992",
    isbn13: "9791193926970",
    itemId: 355972441,
    priceSales: 25200,
    priceStandard: 28000,
    mallType: "BOOK",
    stockStatus: "",
    mileage: 1400,
    cover:
      "https://image.aladin.co.kr/product/35597/24/coversum/k862036992_1.jpg",
    categoryId: 6627,
    categoryName:
      "국내도서>컴퓨터/모바일>프로그래밍 개발/방법론>웹 서비스/웹 프로그래밍",
    publisher: "제이펍",
    salesPoint: 613,
    adult: false,
    fixedPrice: true,
    customerReviewRank: 10,
    subInfo: {},
    isfavorit: false,
  },
  {
    title: "프론트엔드 성능 최적화 가이드 - 웹 개발 스킬을 한 단계 높여 주는",
    link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=304371832&amp;partner=openAPI&amp;start=api",
    author: "유동균 (지은이)",
    pubDate: "2022-11-15",
    description:
      "수많은 기업의 웹 서비스 성능을 컨설팅하고, 삼성 SSAFY, 프로그래머스, 인프런, 스터디파이 등 강의 플랫폼에서 최적화 및 개발 강의를 진행한 경험을 책에 고스란히 녹여 냈다. 이론보다는 실습이 중요함을 강조하며 현장감 있게 구성했다.",
    isbn: "8966263747",
    isbn13: "9788966263745",
    itemId: 304371832,
    priceSales: 19800,
    priceStandard: 22000,
    mallType: "BOOK",
    stockStatus: "",
    mileage: 1100,
    cover:
      "https://image.aladin.co.kr/product/30437/18/coversum/8966263747_1.jpg",
    categoryId: 2662,
    categoryName: "국내도서>컴퓨터/모바일>웹디자인/홈페이지>웹기획",
    publisher: "인사이트",
    salesPoint: 866,
    adult: false,
    fixedPrice: true,
    customerReviewRank: 10,
    seriesInfo: {
      seriesId: 90333,
      seriesLink:
        "http://www.aladin.co.kr/shop/common/wseriesitem.aspx?SRID=90333&amp;partner=openAPI",
      seriesName: "프로그래밍 인사이트 Programming Insight ",
    },
    subInfo: {},
    isfavorit: false,
  },
  {
    title:
      "프런트엔드 개발을 위한 테스트 입문 - 프런트엔드 테스트 기초 지식부터 UI 컴포넌트 테스트, E2E 테스트 등 상황에 맞는 테스트 전략까지",
    link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=340935603&amp;partner=openAPI&amp;start=api",
    author: "요시이 다케후미 (지은이), 원밀리언라인즈코딩(배언수) (옮긴이)",
    pubDate: "2024-06-21",
    description:
      "최신 웹 애플리케이션에서는 품질과 유지보수성을 위해 테스트 자동화가 중요하지만, 테스트 코드를 작성해본 경험이 없어 테스트 코드 작성을 어려워하는 개발자가 많다. 이 책은 테스트 코드를 처음 작성하는 프런트엔드 개발자를 대상으로, 기본적인 테스트 코드 작성법은 물론 상황별 테스트 코드 작성법, 다양한 도구 사용법까지 풍부한 예제와 함께 설명한다.",
    isbn: "K982931181",
    isbn13: "9791193926260",
    itemId: 340935603,
    priceSales: 25200,
    priceStandard: 28000,
    mallType: "BOOK",
    stockStatus: "",
    mileage: 1400,
    cover:
      "https://image.aladin.co.kr/product/34093/56/coversum/k982931181_1.jpg",
    categoryId: 2724,
    categoryName: "국내도서>컴퓨터/모바일>컴퓨터 공학>소프트웨어 공학",
    publisher: "제이펍",
    salesPoint: 679,
    adult: false,
    fixedPrice: true,
    customerReviewRank: 10,
    subInfo: {},
    isfavorit: false,
  },
  {
    title:
      "프런트엔드 개발을 위한 보안 입문 - 기초 보안 지식부터 XSS, CSRF 등 프런트엔드를 노리는 사이버 공격까지",
    link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=330496897&amp;partner=openAPI&amp;start=api",
    author: "히라노 마사시 (지은이), 이춘혁 (옮긴이)",
    pubDate: "2024-01-02",
    description:
      "프런트엔드를 제대로 구현한다면 이러한 XSS 공격뿐만 아니라 여러 사이버 공격을 막을 수 있다. 이 책을 통해 취약성을 조사하고, 근본 원인을 이해하고, 자신의 애플리케이션을 사이버 공격으로부터 보호해보자.",
    isbn: "K222937896",
    isbn13: "9791192987552",
    itemId: 330496897,
    priceSales: 23400,
    priceStandard: 26000,
    mallType: "BOOK",
    stockStatus: "",
    mileage: 1300,
    cover:
      "https://image.aladin.co.kr/product/33049/68/coversum/k222937896_1.jpg",
    categoryId: 387,
    categoryName: "국내도서>컴퓨터/모바일>OS/Networking>네트워크 보안/해킹",
    publisher: "제이펍",
    salesPoint: 336,
    adult: false,
    fixedPrice: true,
    customerReviewRank: 10,
    subInfo: {},
    isfavorit: false,
  },
];
